### ISSUE TITLE
Question: Passing handle to factory class

### ISSUE THREAD

**Issue by dineshbvadhia** [T-baby/pondpond#3]
Using the Dog example, I want to pass a database handle (db) to either class Dog or PooledDogFactory(PooledObjectFactory) to create the pool object from storage. How can this be achieved?

**Comment by T-baby** [comment]
You can refer to the documentation by first declaring a Factory class for the database connection object, which is created and returned in the createInstance function of this class.

For database connection objects it is recommended to set `time_between_eviction_runs` to -1 to disable auto-recovery, which extends the time set in `time_between_eviction_runs`.

**Comment by dineshbvadhia** [comment]
A bit more detail. I have a fastapi startup function:
```
def app_startup()():
	dao = blahblah() #creates a database connection
```
I now want to pass the db connection to pond to create an object pool and on success return to app_startup(). How to achieve this?

**Comment by T-baby** [comment]
There's no way to do that at the moment, so I recommend defining the initialization of the database connection object in the createInstance function of the class that implements PooledObjectFactory.

You should use an object pool to manage object creation and destruction.

When a custom Factory class is registered with Pond, Pond automatically uses the custom Factory class's createInstance function to automatically create objects until the maximum number of object pools is reached.

**Comment by dineshbvadhia** [comment]
Is it possible to pass the dao like this?
```
class PooledDogFactory(PooledObjectFactory):
    def __init__(self, dao): -> None
        self.dao = dao
```
If so, then the next step is to get the createInstance function and the Dog class to use the dao.

**Comment by T-baby** [comment]
```python
class PooledDogFactory(PooledObjectFactory):
    def createInstance(self) -> PooledObject:
        database_connection = create_database_connection()
        return PooledObject(database_connection)

    def destroy(self, pooled_object: PooledObject):
        pooled_object.keeped_object.close()
        del pooled_object

    def reset(self, pooled_object: PooledObject) -> PooledObject:
        pooled_object.keeped_object.re_connect()
        return pooled_object

    def validate(self, pooled_object: PooledObject) -> bool:
        return pooled_object.keeped_object.is_connect()
```

You should not initialize the database connection object externally, but in the Factory class.

**Comment by dineshbvadhia** [comment]
Ok thank-you for your patience :)
