### ISSUE TITLE
Question: Is reset the same as a replace?

### ISSUE THREAD

**Issue by dineshbvadhia** [T-baby/pondpond#4]
Using the Dog example:

`factory = PooledDogFactory(pooled_maxsize=10, least_one=False)`

I want to borrow (in strict terms, I want to 'take' or 'remove') a Dog object from the pool, use the object and discard it (ie. the object is not recycled because the object has been changed). Assume `time_between_eviction_runs` is set to -1.

If the object is not recycled, is a new object created to replace the borrowed (or taken) one with the 'reset' method?

**Comment by T-baby** [comment]
Your guess is right 😄.

If an object is borrowed from the Pond and not recycled, the object may be reclaimed.

If the object is not reclaimed, it will not be in the Pond the next time it is borrowed, another object will be borrowed when it is in the Pond, and a new one will be created if it is not.

**Comment by dineshbvadhia** [comment]
> If an object is borrowed from the Pond and not recycled, the object may be reclaimed

In my case, the aim is to ensure there are always `pooled_maxsize=n` objects in the pool because the time for object creation is high.

Is the borrowed but not recycled object reclaimed automatically (ie. re-created automatically) or do I have to reclaim it using reset?

**Comment by T-baby** [comment]
There's no automatic recycling, but if you need to reset the object during recycling, you can implement that in reset(), which will be called automatically when you recycled it to the Pond manually.

**Comment by dineshbvadhia** [comment]
> ... implement that in reset(), which will be called automatically when you return it to the Pond manually

Please show this with the Dog example?

**Comment by T-baby** [comment]
```python
class Dog:
    name: str
    validate_result:bool = True


class PooledDogFactory(PooledObjectFactory):
    def createInstance(self) -> PooledObject:
        dog = Dog()
        dog.name = "puppy"
        return PooledObject(dog)

    def destroy(self, pooled_object: PooledObject):
        del pooled_object

    def reset(self, pooled_object: PooledObject) -> PooledObject:
        """
        The desired reset action you intend to execute. 
        Upon recycling the Dog object, Pond searches for its factory class and invokes its reset(Dog).
        """
        return pooled_object

    def validate(self, pooled_object: PooledObject) -> bool:
        return pooled_object.keeped_object.validate_result
```

**Comment by dineshbvadhia** [comment]
A related question: Say, I have a set of 10 dog objects in my pool with `pooled_maxsize=4` ie.
```
dog0 = d0
dog1 = d1
...
dog9 = d9
```
There are now 4 sets (`pooled_maxsize=4`) of 10 dog objects (the `pooled_object`)

If I borrow dog2 and reclaim it with reset then the entire `pooled_object` (of 10 dogs) will be reclaimed - is this correct? If so, is there a way to reclaim only dog2?

**Comment by T-baby** [comment]
When you implement the reset function of the PooledObjectFactory abstract class, it will reset() every time you return an object, whether it is returned to the pool or not. The only object reset() will be the one you returned.

It is recommended that the pooled_maxsize parameter match the number you will be using and not be too different.

**Comment by dineshbvadhia** [comment]
> It is recommended that the pooled_maxsize parameter match the number you will be using and not be too different.

In the example, there are 4 sets (`pooled_maxsize`=4) of 10 dog objects each (the `pooled_object`) = 40 objects. Is the recommendation `pooled_maxsize`=10 or =4?

**Comment by T-baby** [comment]
pooled_maxsize=10 would be a better fit, and Pond will automatically recycle objects that are not needed.

**Comment by dineshbvadhia** [comment]
Hi. Returning to this question to get further clarification. I have 4 unique objects (which are very large numpy arrays) ie.
```
dog0 
dog1
dog2
dog3
```
The system requirements are high-performance with high-concurrency. 

Once an object, for example `dog2` is borrowed it is not returned to the object pool because it has changed. This means, the borrowed object should be replaced immediately to meet the system requirements.

Given this, how is the `createInstance` of `PooledDogFactory()` created ie. are there 4 different PooledDogFactory's for dog0, dog1, dog2 and dog3?

Also, what is the optimal `pooled_maxsize`?

I'm using the suggested sample code at https://github.com/T-baby/pondpond/issues/4#issuecomment-1929154450.
